<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>b8097081-2b2b-421b-b5b0-aaba3ac5f2b6</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RentApp.Application\RentApp.Application.csproj" />
    <ProjectReference Include="..\RentApp.Domain\RentApp.Domain.csproj" />
    <ProjectReference Include="..\RentApp.Infrastructure\RentApp.Infrastructure.csproj" />
    <ProjectReference Include="..\RentApp.Persistence\RentApp.Persistence.csproj" />
  </ItemGroup>

</Project>
